export type TradeSafety = 'safe' | 'design' | 'supervised'

export type TradePractice = {
  title: string
  objective: string
  deliverable: string
  safety: TradeSafety
}

export type TradeStage = {
  number: string
  title: string
  level: string
  summary: string
  principles: string[]
  skills: string[]
  practices: TradePractice[]
  project: string
}

export type TradeRoute = {
  id: string
  name: string
  subtitle: string
  target: string
  safetyNote: string
  stages: TradeStage[]
}

const p = (title: string, objective: string, deliverable: string, safety: TradeSafety = 'safe'): TradePractice => ({ title, objective, deliverable, safety })

export const tradeRoutes: TradeRoute[] = [
  {
    id: 'drywall',
    name: 'Panel de yeso',
    subtitle: 'Muros, plafones, juntas, reparación y acabado profesional',
    target: 'Ser capaz de replantear, armar, forrar, tratar juntas, reparar y entregar sistemas de panel de yeso con buena planeación, nivel, plomo y acabado.',
    safetyNote: 'Corte, polvo, trabajo en altura y fijaciones requieren protección adecuada. Muros con requisitos contra incendio, acústicos o estructurales deben seguir el sistema especificado por fabricante/proyecto.',
    stages: [
      {
        number: '01', title: 'Herramientas, seguridad y replanteo', level: 'Iniciación',
        summary: 'Aprende a medir, marcar y preparar un trabajo antes de cortar una sola placa. La precisión del replanteo determina la calidad de todo lo que sigue.',
        principles: ['Medir dos veces y marcar referencias claras.', 'Distinguir estructura, revestimiento y acabado.', 'Controlar polvo, filos y ergonomía desde el inicio.'],
        skills: ['Tipos y espesores de panel', 'Perfiles metálicos y accesorios', 'Cinta, nivel y escuadra', 'Lectura de croquis', 'Replanteo en piso y techo', 'Cálculo básico de materiales', 'Manejo y almacenamiento de placas'],
        practices: [
          p('Replantea un muro de 1.20 m', 'Marcar eje, caras y ubicación de vano sobre una superficie de práctica.', 'Croquis acotado + marcas verificadas'),
          p('Inventario de herramientas', 'Identificar herramienta, función y riesgo antes de usarla.', 'Ficha de 12 herramientas con uso correcto'),
          p('Cuantifica una pared', 'Estimar placas, perfiles, tornillos y desperdicio.', 'Lista de materiales con supuestos')
        ],
        project: 'Plano y replanteo de un muro didáctico'
      },
      {
        number: '02', title: 'Estructura de muros', level: 'Básico',
        summary: 'Construye el esqueleto: canales, postes, modulación, vanos y refuerzos. Un acabado perfecto no corrige una estructura fuera de plomo.',
        principles: ['La modulación debe responder al sistema de placa.', 'Aberturas requieren refuerzo y transferencia de cargas del propio sistema.', 'Plomo, nivel y escuadra se revisan durante, no al final.'],
        skills: ['Canal superior e inferior', 'Separación de postes', 'Corte de perfiles', 'Fijación mecánica de práctica', 'Esquinas y encuentros', 'Vanos para puertas', 'Refuerzos para accesorios', 'Control de plomo y escuadra'],
        practices: [
          p('Bastidor de 60 × 90 cm', 'Armar un marco pequeño y comprobar diagonales.', 'Bastidor estable con registro de medidas'),
          p('Vano de puerta a escala', 'Practicar montantes laterales y dintel sin carga estructural.', 'Módulo con vano correctamente escuadrado'),
          p('Corrección de descuadre', 'Introducir un error y corregirlo mediante diagonales y referencias.', 'Antes/después con medidas')
        ],
        project: 'Muro de entrenamiento con vano'
      },
      {
        number: '03', title: 'Corte y colocación de placas', level: 'Básico',
        summary: 'Aprende a medir, cortar, presentar y atornillar placas sin romper bordes, hundir en exceso tornillos ni crear juntas innecesarias.',
        principles: ['Planear juntas antes de cortar reduce desperdicio.', 'El tornillo sujeta la placa sin destruir el papel.', 'Bordes y juntas se preparan para facilitar el acabado.'],
        skills: ['Corte recto', 'Cortes interiores', 'Aberturas para cajas', 'Orientación de placas', 'Separación de tornillos', 'Profundidad de tornillo', 'Juntas de borde', 'Control de desperdicio'],
        practices: [
          p('Corta 6 piezas exactas', 'Lograr cortes repetibles con tolerancia pequeña.', 'Tabla de medida nominal vs. real'),
          p('Abertura para caja de práctica', 'Transferir medidas y cortar sin sobredimensionar.', 'Placa con abertura ajustada'),
          p('Panel atornillado', 'Practicar separación y profundidad uniforme.', 'Muestra con tornillos correctamente asentados')
        ],
        project: 'Forrado completo del muro didáctico'
      },
      {
        number: '04', title: 'Detalles, encuentros y plafones', level: 'Intermedio',
        summary: 'Resuelve esquinas, encuentros, cambios de plano, plafones y elementos que normalmente revelan errores de ejecución.',
        principles: ['Los detalles se deciden antes de cerrar.', 'Los encuentros deben permitir acabado continuo y estable.', 'Trabajo sobre cabeza requiere control adicional de seguridad y soporte.'],
        skills: ['Esquinas interiores', 'Esquinas exteriores', 'Guardavivos', 'Encuentros con muro existente', 'Plafón suspendido conceptual', 'Cajillos', 'Registros', 'Preparación para instalaciones'],
        practices: [
          p('Esquina interior y exterior', 'Construir dos muestras y comparar secuencia de acabado.', 'Módulo de esquina doble'),
          p('Cajillo pequeño', 'Resolver cambios de plano y continuidad de perfiles.', 'Cajillo didáctico nivelado'),
          p('Coordinación con caja eléctrica', 'Preparar refuerzo y abertura sin cableado de red.', 'Detalle documentado de caja y placa', 'supervised')
        ],
        project: 'Módulo de esquina + plafón didáctico'
      },
      {
        number: '05', title: 'Cintas, compuesto y acabado', level: 'Intermedio',
        summary: 'Domina la parte más visible del oficio: tratar juntas, tornillos y esquinas en capas controladas hasta desaparecer transiciones sin crear montañas de compuesto.',
        principles: ['Capas delgadas y progresivas superan una capa gruesa.', 'El lijado corrige poco; la aplicación correcta corrige mucho.', 'La luz rasante revela defectos que la vista frontal oculta.'],
        skills: ['Preparación de compuesto', 'Cinta de papel/malla según sistema', 'Primera capa', 'Segunda capa', 'Capa de terminación', 'Tornillos', 'Esquinas', 'Lijado y control de polvo', 'Niveles de acabado'],
        practices: [
          p('Junta de 60 cm', 'Aplicar cinta y tres capas controlando ancho y transición.', 'Muestra terminada + fotos por capa'),
          p('Tornillos invisibles', 'Rellenar fijaciones sin dejar cráter ni exceso.', 'Panel con 12 fijaciones acabadas'),
          p('Inspección con luz rasante', 'Detectar bordes, huecos y ondas.', 'Checklist de defectos + correcciones')
        ],
        project: 'Panel de acabado listo para pintura'
      },
      {
        number: '06', title: 'Aislamiento, acústica y sistemas especiales', level: 'Avanzado',
        summary: 'Comprende cómo aislamiento, capas, sellos y desacoplamientos cambian el desempeño acústico, térmico y de resistencia al fuego del sistema.',
        principles: ['El desempeño depende del sistema completo, no de una sola placa.', 'Penetraciones pueden degradar acústica o fuego.', 'Sistemas certificados deben respetarse como conjunto.'],
        skills: ['Aislamiento térmico', 'Aislamiento acústico', 'Sellos perimetrales', 'Doble placa', 'Canales resilientes conceptuales', 'Placas resistentes a humedad', 'Placas resistentes al fuego', 'Tratamiento de penetraciones'],
        practices: [
          p('Caja acústica comparativa', 'Comparar una muestra vacía y otra con aislamiento.', 'Registro cualitativo de diferencia'),
          p('Detalle de doble placa', 'Planear traslape de juntas entre capas.', 'Croquis de juntas y fijaciones'),
          p('Audita penetraciones', 'Detectar puntos débiles en un caso simulado.', 'Lista de riesgos y solución propuesta', 'design')
        ],
        project: 'Muro de desempeño especificado'
      },
      {
        number: '07', title: 'Reparación, diagnóstico y calidad', level: 'Avanzado',
        summary: 'Aprende a distinguir defecto cosmético, movimiento, humedad y falla de soporte antes de reparar. Reparar sin diagnosticar crea reincidencias.',
        principles: ['La causa se corrige antes que el acabado.', 'Una reparación debe integrarse mecánica y visualmente.', 'La calidad se inspecciona con criterios repetibles.'],
        skills: ['Grietas', 'Golpes y perforaciones', 'Tornillos visibles', 'Juntas marcadas', 'Daño por humedad', 'Ondulaciones', 'Parches', 'Checklist de entrega'],
        practices: [
          p('Parche pequeño', 'Reparar una perforación y ocultar la transición.', 'Parche terminado y evaluado'),
          p('Diagnóstico de grietas', 'Clasificar 6 casos por causa probable.', 'Árbol causa → verificación → reparación'),
          p('Inspección de un muro', 'Calificar planeidad, juntas, esquinas y tornillos.', 'Reporte de calidad con prioridades')
        ],
        project: 'Clínica de reparaciones'
      },
      {
        number: '08', title: 'Proyecto profesional de panel de yeso', level: 'Profesional',
        summary: 'Integra medición, materiales, estructura, placas, acabado, presupuesto, secuencia y control de calidad en un proyecto completo de práctica.',
        principles: ['El trabajo profesional comienza con alcance y termina con evidencia.', 'Material, tiempo y desperdicio se controlan desde la planeación.', 'La entrega debe poder auditarse.'],
        skills: ['Levantamiento', 'Croquis', 'Cuantificación', 'Presupuesto', 'Secuencia de trabajo', 'Control de desperdicio', 'Control de calidad', 'Entrega y documentación'],
        practices: [
          p('Cotización completa', 'Presupuestar un muro y plafón ficticios.', 'Presupuesto con cantidades y supuestos', 'design'),
          p('Simulación de obra', 'Planear jornada, herramientas, materiales y orden de operaciones.', 'Plan de ejecución'),
          p('Entrega final', 'Construir y documentar un módulo completo.', 'Dossier con fotos, mediciones y checklist', 'supervised')
        ],
        project: 'Habitación didáctica: muro, vano, esquina y acabado'
      }
    ]
  },
  {
    id: 'masonry',
    name: 'Albañilería',
    subtitle: 'Mezclas, muros, niveles, aplanados, pisos y reparación',
    target: 'Ser capaz de ejecutar trabajos de albañilería no estructural con control de medida, mezcla, nivel, plomo, acabado y diagnóstico; y comprender cuándo una intervención requiere proyecto estructural.',
    safetyNote: 'Cargas, demoliciones y elementos estructurales no se improvisan. Cimentaciones, castillos, cadenas, losas y modificaciones estructurales deben apegarse al proyecto y supervisión profesional correspondiente.',
    stages: [
      { number:'01', title:'Seguridad, medición y materiales', level:'Iniciación', summary:'Construye hábitos de obra: orden, medición, niveles, herramientas y reconocimiento de materiales.', principles:['Medir y trazar antes de mezclar.','Mantener materiales limpios y dosificados.','Distinguir trabajo de acabado de trabajo estructural.'], skills:['Cinta y flexómetro','Nivel de burbuja','Plomada','Hilo y reglas','Bloque, tabique y piezas','Cemento, cal y agregados','Agua de mezclado','EPP y orden'], practices:[p('Trazo de escuadra 3-4-5','Construir una escuadra de práctica y verificar diagonales.','Croquis + medidas'),p('Banco de niveles','Comparar nivel, plomada y regla en distintas superficies.','Registro de desviaciones'),p('Reconoce materiales','Clasificar muestras y anotar uso típico.','Ficha de materiales')], project:'Zona de trazo y control geométrico' },
      { number:'02', title:'Morteros y mezclas', level:'Básico', summary:'Aprende qué función cumple cada componente y cómo consistencia, dosificación y curado cambian el resultado.', principles:['No existe una mezcla universal.','El agua excesiva suele deteriorar desempeño y control.','La consistencia se evalúa según uso.'], skills:['Dosificación por volumen','Consistencia','Mortero de pega','Mortero de aplanado','Concreto conceptual','Rendimiento','Tiempo de trabajabilidad','Curado'], practices:[p('Tres consistencias de mortero','Preparar lotes pequeños y comparar comportamiento.','Tabla de proporción/consistencia'),p('Prueba de trabajabilidad','Aplicar el mismo mortero en pequeñas muestras.','Fotos + observaciones'),p('Estimación de rendimiento','Medir cuánto cubre un lote pequeño.','m² o piezas por lote')], project:'Muestrario de mezclas y acabados' },
      { number:'03', title:'Muros de bloque y tabique', level:'Básico', summary:'Domina cama de mortero, juntas, alineación, trabado y ritmo de control geométrico.', principles:['Cada hilada se controla antes de seguir.','Las juntas deben ser consistentes.','El aparejo distribuye juntas y mejora continuidad.'], skills:['Primera hilada','Cama de mortero','Juntas verticales','Aparejo','Nivel de hilada','Plomo de muro','Hilo guía','Cortes de piezas'], practices:[p('Muro de 6 bloques','Levantar una muestra y documentar cada hilada.','Módulo pequeño'),p('Esquina a plomo','Formar una esquina de práctica con control de 90°.','Esquina medida'),p('Corrección de hilada','Detectar y corregir desviación antes de fraguar.','Registro de corrección')], project:'Muro bajo de entrenamiento' },
      { number:'04', title:'Vanos, encuentros y detalles', level:'Intermedio', summary:'Resuelve esquinas, encuentros y vanos entendiendo cómo cambia el aparejo y cuándo aparece una función estructural.', principles:['Los vanos cambian el flujo de cargas.','Los detalles deben corresponder al sistema constructivo.','No se corta un elemento existente sin conocer su función.'], skills:['Esquinas','Encuentros en T','Remates','Vanos','Dinteles conceptuales','Mochetas','Anclajes de proyecto','Compatibilidad con instalaciones'], practices:[p('Encuentro en T a escala','Planear aparejo de dos muros.','Módulo pequeño'),p('Vano simulado','Replantear abertura y remates sin carga.','Croquis + ejecución'),p('Mapa de riesgos','Identificar qué detalles requieren cálculo/proyecto.','Checklist de límites','design')], project:'Muro con esquina y vano didáctico' },
      { number:'05', title:'Refuerzo y elementos de concreto', level:'Avanzado', summary:'Estudia acero, cimbra, recubrimiento y secuencia de colado para comprender el sistema, reservando dimensionamiento y ejecución estructural al proyecto competente.', principles:['El acero trabaja donde el proyecto lo define.','Recubrimiento, anclaje y posición importan.','Cambiar una sección estructural no es una decisión de oficio aislada.'], skills:['Acero de refuerzo conceptual','Traslapes y anclajes conceptuales','Castillos','Cadenas','Cimbra','Recubrimiento','Vibrado y compactación','Curado'], practices:[p('Jaula de refuerzo didáctica','Armar con varilla delgada/alambre un modelo no estructural.','Modelo etiquetado','supervised'),p('Cimbra de muestra','Construir una pequeña forma para comprender aplome y rigidez.','Cimbra didáctica','supervised'),p('Lee un detalle estructural','Identificar sección, acero y notas sin modificar diseño.','Ficha interpretativa','design')], project:'Modelo de confinamiento estructural' },
      { number:'06', title:'Aplanados, firmes y pisos', level:'Intermedio', summary:'Controla preparación de superficie, maestras, espesores, planeidad y acabado.', principles:['La adherencia comienza con la preparación.','Las maestras convierten acabado en geometría controlada.','Espesor excesivo suele indicar un problema previo.'], skills:['Preparación de soporte','Maestras','Aplanado grueso','Aplanado fino','Planeidad','Firmes','Pendientes','Acabado superficial'], practices:[p('Aplanado de 50 × 50 cm','Preparar, aplicar y reglear una muestra.','Panel terminado'),p('Pendiente controlada','Formar una pequeña pendiente con referencias.','Medición de desnivel'),p('Inspección de planeidad','Usar regla y luz para localizar huecos.','Mapa de desviaciones')], project:'Panel de acabados minerales' },
      { number:'07', title:'Patologías y reparación', level:'Avanzado', summary:'Distingue fisuras, humedad, desprendimiento y asentamiento aparente antes de intervenir.', principles:['No toda grieta es cosmética.','Humedad requiere encontrar origen.','Reparar evidencia sin causa produce reincidencia.'], skills:['Fisuras vs grietas','Desprendimientos','Salitre','Humedad','Asentamientos aparentes','Juntas deterioradas','Reparación de aplanado','Inspección y seguimiento'], practices:[p('Atlas de grietas','Clasificar casos por patrón y nivel de alerta.','Ficha de diagnóstico','design'),p('Parche de aplanado','Reparar una muestra dañada controlando transición.','Parche terminado'),p('Ruta de humedad','Plantear pruebas no destructivas para localizar origen.','Árbol de diagnóstico','design')], project:'Clínica de patologías de obra' },
      { number:'08', title:'Proyecto profesional de albañilería', level:'Profesional', summary:'Integra trazo, materiales, cuantificación, ejecución de muestra, calidad y presupuesto.', principles:['La secuencia reduce retrabajo.','La geometría se documenta.','El alcance estructural se separa y deriva al profesional correspondiente.'], skills:['Levantamiento','Cuantificación','Rendimientos','Presupuesto','Secuencia','Control de calidad','Desperdicio','Entrega'], practices:[p('Presupuesta un muro','Calcular piezas, mortero, desperdicio y mano de obra ficticia.','Presupuesto','design'),p('Plan de ejecución','Crear secuencia desde trazo hasta acabado.','Cronograma corto','design'),p('Módulo final','Ejecutar un muro bajo y acabado con checklist.','Dossier final','supervised')], project:'Muro didáctico completo con acabado' }
    ]
  },
  {
    id: 'construction',
    name: 'Construcción',
    subtitle: 'Obra, cimentación, concreto, sistemas y control de calidad',
    target: 'Comprender y coordinar una obra de pequeña escala, interpretar detalles, cuantificar y supervisar procesos; ejecutar solo tareas compatibles con tu competencia y con el proyecto estructural.',
    safetyNote: 'Cimentaciones, estructuras, excavaciones, trabajos en altura y demoliciones pueden implicar riesgo grave. La plataforma enseña criterio, secuencia, control y maquetas; el diseño y ejecución estructural real requieren responsables competentes.',
    stages: [
      { number:'01', title:'Cómo funciona una obra', level:'Iniciación', summary:'Aprende fases, actores, documentos, seguridad y control básico.', principles:['La obra se ejecuta desde documentos coordinados.','Cada actividad tiene precondiciones y controles.','Seguridad y calidad se planean.'], skills:['Fases de obra','Planos y especificaciones','Bitácora','EPP y señalización','Trazabilidad','Tolerancias','Control de materiales'], practices:[p('Secuencia una casa','Ordenar 25 actividades de una vivienda.','Diagrama de precedencias','design'),p('Bitácora de práctica','Registrar cambios y decisiones de un caso.','Bitácora de 1 semana','design'),p('Inspección de sitio simulado','Detectar 15 riesgos/defectos en fotografías o caso.','Checklist')], project:'Plan general de obra' },
      { number:'02', title:'Trazo, terreno y excavación', level:'Básico', summary:'Comprende ejes, niveles, bancos de referencia, excavación y preparación de desplante.', principles:['Un error de trazo se amplifica en toda la obra.','Los niveles deben referenciarse a un punto estable.','Excavaciones requieren evaluación de estabilidad y servicios.'], skills:['Ejes','Bancos de nivel','Escuadras','Niveles','Terreno','Excavación conceptual','Rellenos','Compactación conceptual'], practices:[p('Trazo a escala real','Marcar ejes de una habitación en patio o maqueta.','Plano + verificación diagonal'),p('Circuito de nivelación','Transferir una cota entre puntos.','Registro de cotas'),p('Plan de excavación','Analizar riesgos y secuencia de un caso.','Método seguro propuesto','design')], project:'Replanteo completo de una planta' },
      { number:'03', title:'Cimentaciones', level:'Intermedio', summary:'Entiende por qué una cimentación depende de suelo, cargas, geometría y proyecto estructural.', principles:['No existe una zapata universal.','Suelo y estructura se analizan juntos.','La ejecución debe reproducir dimensiones, niveles, acero y concreto del proyecto.'], skills:['Capacidad de suelo conceptual','Zapatas','Cimientos corridos','Losas de cimentación conceptuales','Plantilla','Acero','Recubrimiento','Drenaje y humedad'], practices:[p('Modelo de zapata','Construir maqueta seccionada con capas etiquetadas.','Modelo didáctico','supervised'),p('Lee un plano de cimentación','Identificar ejes, secciones, niveles y notas.','Hoja interpretativa','design'),p('Checklist precolado','Crear puntos de inspección antes del concreto.','Checklist profesional','design')], project:'Expediente de cimentación de una vivienda ficticia' },
      { number:'04', title:'Concreto, acero y cimbra', level:'Intermedio', summary:'Aprende secuencia de armado, cimbra, colado, compactación, curado y control.', principles:['La resistencia depende del conjunto de materiales, dosificación y curado.','La posición del acero es parte del diseño.','La cimbra debe resistir y mantener geometría.'], skills:['Propiedades del concreto','Revenimiento conceptual','Acero de refuerzo','Recubrimiento','Separadores','Cimbra','Colado','Vibrado','Curado'], practices:[p('Cubo de concreto didáctico','Preparar pequeña muestra no estructural y documentar curado.','Registro de lote','supervised'),p('Cimbra pequeña','Construir molde y revisar escuadra/estanqueidad.','Cimbra de práctica','supervised'),p('Audita un armado en plano','Comparar modelo con detalle proporcionado.','Lista de discrepancias','design')], project:'Elemento de concreto no estructural de entrenamiento' },
      { number:'05', title:'Muros y sistemas constructivos', level:'Intermedio', summary:'Compara mampostería, sistemas ligeros y elementos de confinamiento dentro del proyecto.', principles:['El sistema define detalles y secuencia.','Compatibilizar instalaciones evita cortes posteriores.','Muros estructurales no se modifican por conveniencia.'], skills:['Mampostería','Muros divisorios','Confinamiento','Juntas','Aberturas','Anclajes','Compatibilización MEP','Control geométrico'], practices:[p('Comparativa de sistemas','Elegir sistema para 4 casos y justificar.','Matriz técnica','design'),p('Coordinación de instalaciones','Detectar conflictos en un plano.','Plano marcado','design'),p('Detalle de vano','Interpretar capas y refuerzos de un caso.','Croquis técnico','design')], project:'Muro coordinado de entrenamiento' },
      { number:'06', title:'Losas, cubiertas y escaleras', level:'Avanzado', summary:'Comprende geometría, apoyos, pendientes, impermeabilización y secuencias, sin asumir diseño estructural.', principles:['La dirección de trabajo estructural importa.','Agua y estructura se resuelven juntas en cubiertas.','Escaleras deben coordinar huella, peralte, altura libre y soporte.'], skills:['Tipos de losa','Apoyos','Cimbra conceptual','Pendientes','Cubiertas','Impermeabilización','Geometría de escaleras','Detalles de borde'], practices:[p('Maqueta de losa','Representar apoyos y dirección de trabajo.','Modelo etiquetado','design'),p('Calcula escalera geométrica','Resolver huellas/peraltes de un caso sin diseñar estructura.','Plano de escalera','design'),p('Drenaje de cubierta','Proponer pendientes y bajadas en planta.','Plano de pendientes','design')], project:'Cubierta y escalera de vivienda ficticia' },
      { number:'07', title:'Instalaciones, envolvente y calidad', level:'Avanzado', summary:'Coordina electricidad, agua, drenaje, ventilación, impermeabilización y acabados para evitar interferencias y fallas.', principles:['La coordinación ocurre antes de cerrar.','Penetraciones deben resolverse por sistema.','Calidad se inspecciona por hitos.'], skills:['Coordinación eléctrica','Coordinación hidráulica','Drenaje','Impermeabilización','Ventanas y sellos','Puentes térmicos conceptuales','Pruebas','Punch list'], practices:[p('Clash manual','Encontrar choques entre 3 planos.','Lista de conflictos','design'),p('Checklist por etapa','Crear inspección antes de cerrar muros.','Checklist','design'),p('Punch list de habitación','Inspeccionar una habitación real sin intervenir.','Reporte fotográfico')], project:'Plan de control de calidad de vivienda' },
      { number:'08', title:'Planeación, costos y supervisión', level:'Profesional', summary:'Convierte un proyecto en cantidades, presupuesto, programa y control.', principles:['Costo, tiempo y alcance están conectados.','Los rendimientos son hipótesis que se validan.','Cambios deben documentarse.'], skills:['Catálogo de conceptos','Generadores','Rendimientos','Precios unitarios conceptuales','Programa de obra','Ruta crítica básica','Control de cambios','Estimaciones'], practices:[p('Catálogo de conceptos','Desglosar una vivienda ficticia.','Catálogo con unidades','design'),p('Programa de 12 semanas','Secuenciar actividades y dependencias.','Gantt básico','design'),p('Orden de cambio','Documentar impacto de un cambio ficticio.','Formato completo','design')], project:'Presupuesto y programa de obra' },
      { number:'09', title:'Proyecto maestro de construcción', level:'Profesional+', summary:'Integra desde el terreno hasta la entrega en un caso completo, obligándote a justificar decisiones y detectar límites de responsabilidad.', principles:['Nada se ejecuta sin plano vigente.','Cada hito tiene criterios de aceptación.','Lo estructural y especializado se deriva a responsables competentes.'], skills:['Revisión de proyecto','Planeación de sitio','Compras','Secuencia','Inspección','Coordinación','Costos','Cambios','Entrega'], practices:[p('Preconstrucción','Revisar expediente y crear RFI/pendientes.','Reporte de preconstrucción','design'),p('Simulación de 10 incidencias','Resolver clima, atraso, conflicto y cambio.','Bitácora de decisiones','design'),p('Entrega de vivienda ficticia','Consolidar planos, pruebas, pendientes y manuales.','Expediente final','design')], project:'Gestión integral de una vivienda ficticia' }
    ]
  },
  {
    id: 'architecture',
    name: 'Arquitectura práctica',
    subtitle: 'Planos, espacio, detalles, cuantificación y documentación',
    target: 'Poder levantar, representar, organizar y documentar espacios con criterio constructivo, producir un juego de planos de vivienda y coordinarlo con cantidades y detalles.',
    safetyNote: 'El diseño arquitectónico no sustituye cálculo estructural, proyecto de instalaciones ni responsabilidades legales que correspondan a profesionistas autorizados en cada jurisdicción.',
    stages: [
      { number:'01', title:'Dibujo, escala y lenguaje de planos', level:'Iniciación', summary:'Aprende a leer y producir información gráfica consistente.', principles:['La escala define cuánto detalle cabe.','Las cotas mandan sobre la medición visual.','Cada línea y símbolo debe comunicar algo.'], skills:['Escalas','Tipos de línea','Cotas','Ejes','Niveles','Símbolos','Planta','Corte','Fachada'], practices:[p('Redibuja una habitación','Levantar y dibujar a 1:50.','Planta acotada'),p('Escalas comparadas','Representar el mismo objeto a 1:20, 1:50 y 1:100.','Lámina comparativa'),p('Lee 3 planos','Localizar ejes, niveles, cotas y referencias.','Cuestionario resuelto')], project:'Plano de una habitación existente' },
      { number:'02', title:'Levantamiento y programa', level:'Básico', summary:'Aprende a medir un lugar y convertir necesidades en requerimientos espaciales.', principles:['El programa precede a la forma.','Medir incluye alturas, aperturas y condicionantes.','Los supuestos deben quedar escritos.'], skills:['Levantamiento','Croquis de campo','Fotografías de referencia','Programa arquitectónico','Relaciones funcionales','Usuarios','Mobiliario','Restricciones'], practices:[p('Levantamiento completo','Medir un espacio real pequeño.','Croquis + planta'),p('Programa de vivienda','Convertir necesidades ficticias en áreas/relaciones.','Tabla de programa','design'),p('Diagrama de burbujas','Proponer adyacencias antes de dibujar muros.','3 alternativas','design')], project:'Expediente base de un departamento pequeño' },
      { number:'03', title:'Distribución y ergonomía', level:'Intermedio', summary:'Diseña circulaciones, mobiliario y proporciones que hagan el espacio utilizable.', principles:['Diseñar desde actividades, no solo desde paredes.','La circulación necesita continuidad.','Mobiliario verifica escala y uso.'], skills:['Circulaciones','Zonificación','Mobiliario','Dimensiones funcionales','Privacidad','Iluminación natural conceptual','Ventilación conceptual','Flexibilidad'], practices:[p('Tres distribuciones','Resolver la misma planta de tres maneras.','Comparativa argumentada','design'),p('Prueba de mobiliario','Amueblar a escala y detectar conflictos.','Planta amueblada','design'),p('Recorrido del usuario','Trazar recorridos cotidianos.','Mapa de circulación','design')], project:'Distribución de vivienda compacta' },
      { number:'04', title:'Documentación constructiva', level:'Intermedio', summary:'Convierte una idea en planos capaces de coordinar construcción.', principles:['Toda vista debe referenciarse.','Las cotas deben ser suficientes y no contradictorias.','Los detalles explican lo que la planta no puede.'], skills:['Plantas arquitectónicas','Cortes','Fachadas','Planta de plafones','Acabados','Puertas y ventanas','Detalles','Notas y especificaciones'], practices:[p('Juego mínimo de planos','Preparar planta, 2 cortes y 2 fachadas.','Set coordinado','design'),p('Cuadro de puertas','Catalogar dimensiones y tipos.','Tabla completa','design'),p('Detalle 1:10','Resolver un encuentro de muro-piso.','Detalle constructivo','design')], project:'Juego de planos de vivienda pequeña' },
      { number:'05', title:'Materiales y detalles', level:'Intermedio', summary:'Relaciona intención espacial con capas, encuentros y mantenimiento.', principles:['Cada material tiene espesor y tolerancias.','Los encuentros concentran problemas.','Durabilidad y mantenimiento son parte del diseño.'], skills:['Muros','Pisos','Plafones','Carpinterías','Sellos','Juntas','Impermeabilización conceptual','Detalles de borde'], practices:[p('Matriz de materiales','Elegir materiales para 5 espacios y justificar.','Matriz técnica','design'),p('Detalle de baño','Representar capas de muro/piso en zona húmeda.','Detalle 1:10','design'),p('Auditoría de encuentros','Encontrar 10 puntos que requieren detalle.','Plano marcado','design')], project:'Catálogo de detalles de vivienda' },
      { number:'06', title:'Habitabilidad, accesibilidad y clima', level:'Avanzado', summary:'Integra orientación, luz, ventilación, accesibilidad y confort como criterios medibles.', principles:['El sitio condiciona el proyecto.','Accesibilidad se diseña desde el inicio.','Confort pasivo reduce dependencia de equipos.'], skills:['Orientación','Asoleamiento conceptual','Ventilación cruzada','Iluminación natural','Protección solar','Accesibilidad','Rutas sin barreras','Confort térmico conceptual'], practices:[p('Carta solar simplificada','Analizar fachadas por orientación.','Mapa de decisiones','design'),p('Ruta accesible','Auditar una planta y proponer mejoras.','Plano corregido','design'),p('Estrategias pasivas','Elegir 5 estrategias para un clima dado.','Ficha justificativa','design')], project:'Optimización pasiva de una vivienda' },
      { number:'07', title:'Cuantificación y presupuesto', level:'Avanzado', summary:'Extrae cantidades directamente de planos y relaciona diseño con costo.', principles:['Cada cantidad debe rastrearse al plano.','Los cambios de diseño cambian costo.','Unidades correctas evitan errores masivos.'], skills:['Áreas','Longitudes','Volúmenes','Catálogo de conceptos','Cuantificación','Desperdicio','Costos paramétricos','Comparación de alternativas'], practices:[p('Cuantifica acabados','Medir pisos, muros y plafones de un plano.','Hoja de cantidades','design'),p('Opción A vs B','Comparar costo conceptual de dos acabados.','Matriz costo/beneficio','design'),p('Control de cambios','Actualizar cantidades tras modificar la planta.','Versión comparada','design')], project:'Presupuesto conceptual de vivienda' },
      { number:'08', title:'Coordinación digital y revisión', level:'Profesional', summary:'Aprende a revisar consistencia entre disciplinas y administrar versiones aunque trabajes con herramientas sencillas.', principles:['Coordinar es detectar conflictos antes de obra.','Una versión debe ser inequívoca.','Modelar no reemplaza pensar.'], skills:['Capas y nomenclatura','Versionado','Referencias','Coordinación MEP','Clash manual','BIM conceptual','Revisión de planos','As-built'], practices:[p('Control de versiones','Crear nomenclatura y registro de cambios.','Matriz de versiones','design'),p('Clash arquitectónico-MEP','Revisar un caso con conflictos.','Reporte de coordinación','design'),p('Set para emisión','Revisar consistencia de un juego completo.','Checklist de emisión','design')], project:'Expediente coordinado para construcción' },
      { number:'09', title:'Proyecto maestro de vivienda', level:'Profesional+', summary:'Desarrolla una vivienda desde programa hasta expediente, cuantificación y revisión final.', principles:['Cada decisión debe responder a una necesidad.','El proyecto se prueba con recorridos, medidas y detalles.','La entrega final debe ser construible y auditable.'], skills:['Programa','Concepto','Planta','Cortes','Fachadas','Detalles','Acabados','Cuantificación','Coordinación','Presentación'], practices:[p('Anteproyecto','Resolver tres opciones y elegir una con criterios.','Anteproyecto argumentado','design'),p('Proyecto ejecutivo simplificado','Producir juego coordinado.','PDF/set de planos','design'),p('Revisión cruzada','Auditar el proyecto con 50 puntos.','Punch list + versión corregida','design')], project:'Vivienda pequeña completamente documentada' }
    ]
  },
  {
    id: 'plumbing',
    name: 'Plomería',
    subtitle: 'Agua, drenaje, conexiones, aparatos y diagnóstico',
    target: 'Ser capaz de montar y reparar sistemas domésticos sencillos de agua y drenaje en bancos de práctica, dimensionar conceptualmente y diagnosticar fallas comunes con método.',
    safetyNote: 'Gas, calderas, agua a alta temperatura/presión, conexiones a red pública y modificaciones sanitarias reguladas pueden requerir personal autorizado. La plataforma separa claramente esas tareas.',
    stages: [
      { number:'01', title:'Herramientas, materiales y seguridad', level:'Iniciación', summary:'Reconoce tuberías, conexiones, válvulas y herramientas antes de cortar o pegar.', principles:['El material define el método de unión.','Una unión limpia empieza con corte correcto.','Presión y temperatura limitan componentes.'], skills:['PVC','CPVC','PPR conceptual','PEX conceptual','Cobre conceptual','Válvulas','Herramientas','Selladores y cintas'], practices:[p('Mesa de conexiones','Identificar 20 accesorios y su función.','Inventario etiquetado'),p('Cortes cuadrados','Realizar cortes limpios en retazos.','Muestras verificadas'),p('Rosca de práctica','Aplicar cinta/sellador correctamente en piezas didácticas.','Uniones desmontables')], project:'Kit de conexiones domésticas' },
      { number:'02', title:'Abastecimiento de agua', level:'Básico', summary:'Comprende presión, caudal, recorrido, válvulas y distribución.', principles:['Presión y caudal no son lo mismo.','Pérdidas aumentan con longitud, accesorios y flujo.','Válvulas deben aislar zonas con lógica.'], skills:['Presión','Caudal','Diámetros conceptuales','Líneas fría/caliente','Válvulas de corte','Ramales','Golpe de ariete conceptual','Prueba de fugas'], practices:[p('Banco de agua a baja presión','Montar circuito con depósito elevado o bomba pequeña segura.','Banco sin fugas'),p('Mapa de válvulas','Diseñar aislamiento de cocina y baño.','Diagrama','design'),p('Caudal comparado','Medir litros/minuto en dos configuraciones de manguera.','Tabla de resultados')], project:'Red didáctica de abastecimiento' },
      { number:'03', title:'Drenaje y ventilación', level:'Intermedio', summary:'Aprende gravedad, pendiente, sifones, ventilación y registros.', principles:['El drenaje depende de pendiente y aire.','El sello hidráulico protege contra gases.','Los cambios de dirección deben poder mantenerse.'], skills:['Pendiente','Sifones','Ventilación','Ramales','Bajantes conceptuales','Registros','Diámetros conceptuales','Prueba de escurrimiento'], practices:[p('Canal de pendiente','Construir tramo transparente y variar pendiente.','Registro de flujo'),p('Sifón transparente','Observar sello hidráulico y sifonamiento.','Video/fotos + explicación'),p('Plano sanitario','Trazar aparatos, ramales y ventilación conceptual.','Plano','design')], project:'Banco de drenaje transparente' },
      { number:'04', title:'Uniones y técnicas de montaje', level:'Intermedio', summary:'Practica cortes, preparación, adhesivos, termofusión simulada/con equipo adecuado y conexiones mecánicas.', principles:['La preparación de superficie controla la unión.','Cada sistema tiene tiempos y herramientas.','Una unión torcida transmite esfuerzo.'], skills:['Corte y bisel','Cementado solvente','Roscas','Conexiones mecánicas','PPR conceptual','Soportes','Dilatación','Alineación'], practices:[p('Serie de uniones PVC','Fabricar 6 uniones y luego seccionarlas para inspección.','Muestrario'),p('Marco hidráulico','Montar un rectángulo con válvula y desmontable.','Circuito de práctica'),p('Prueba de estanqueidad baja','Llenar banco seguro y revisar fugas.','Checklist')], project:'Módulo de uniones y válvulas' },
      { number:'05', title:'Aparatos y grifería', level:'Intermedio', summary:'Comprende conexiones, sellos, válvulas y mantenimiento de lavabo, fregadero e inodoro en módulos de práctica.', principles:['Cada aparato necesita acceso para mantenimiento.','Sellar no significa llenar de sellador.','Las conexiones flexibles tienen límites.'], skills:['Lavabo','Fregadero','Inodoro conceptual','Mezcladoras','Llaves angulares','Trampas','Empaques','Flexibles'], practices:[p('Lavabo de entrenamiento','Montar alimentación y trampa en módulo.','Conjunto sin fugas'),p('Cambio de empaque','Diagnosticar goteo en grifo de práctica.','Reparación documentada'),p('Desmontaje ordenado','Desarmar/rearmar una trampa sin perder piezas.','Checklist')], project:'Módulo de lavabo completo' },
      { number:'06', title:'Diseño doméstico y cuantificación', level:'Avanzado', summary:'Traza rutas, calcula cantidades y revisa mantenibilidad.', principles:['Las rutas cortas no siempre son las más mantenibles.','Agua y drenaje tienen lógicas diferentes.','Registros y válvulas deben quedar accesibles.'], skills:['Isométricos','Rutas','Diámetros conceptuales','Pérdidas conceptuales','Pendientes','Ventilación','Lista de materiales','Coordinación con obra'], practices:[p('Isométrico de baño','Dibujar agua y drenaje por separado.','Isométricos','design'),p('Lista de materiales','Cuantificar tubos, codos, tees y válvulas.','BOM','design'),p('Auditoría de accesibilidad','Detectar uniones ocultas problemáticas.','Plano corregido','design')], project:'Proyecto hidrosanitario de baño ficticio' },
      { number:'07', title:'Diagnóstico y reparación', level:'Avanzado', summary:'Localiza fugas, baja presión, drenaje lento y malos olores mediante síntomas y pruebas sencillas.', principles:['Primero delimita el sistema.','Una reparación debe confirmar causa raíz.','No todo drenaje lento se resuelve con químicos.'], skills:['Fuga visible','Fuga oculta conceptual','Baja presión','Obstrucción','Sifonamiento','Olores','Válvula defectuosa','Mantenimiento preventivo'], practices:[p('Clínica de fugas','Preparar 3 fallas en banco de baja presión.','Reporte diagnóstico'),p('Drenaje lento','Comparar obstrucción vs pendiente insuficiente en banco.','Tabla de síntomas'),p('Árbol de diagnóstico','Crear ruta para baja presión.','Diagrama','design')], project:'Clínica hidrosanitaria' },
      { number:'08', title:'Proyecto profesional de plomería', level:'Profesional', summary:'Integra plano, materiales, montaje didáctico, pruebas, presupuesto y entrega.', principles:['Pruebas se planifican antes de cerrar.','Toda válvula y registro debe quedar documentado.','El cliente debe saber aislar y mantener.'], skills:['Levantamiento','Diseño','Cuantificación','Presupuesto','Montaje','Prueba','Corrección','Entrega'], practices:[p('Presupuesto baño','Cotizar materiales y mano de obra ficticia.','Presupuesto','design'),p('Banco baño-cocina','Montar red didáctica combinada.','Sistema probado','supervised'),p('Manual de usuario','Documentar válvulas, mantenimiento y emergencias.','Manual breve','design')], project:'Baño didáctico completamente documentado' }
    ]
  },
  {
    id: 'finishes',
    name: 'Acabados',
    subtitle: 'Pintura, recubrimientos, pisos, impermeabilización y reparación',
    target: 'Ser capaz de preparar superficies, elegir sistemas compatibles, ejecutar muestras y habitaciones completas con control de apariencia, adherencia y durabilidad.',
    safetyNote: 'Solventes, polvos, escaleras y algunos recubrimientos requieren ventilación, EPP y fichas técnicas. Nunca mezcles productos químicos incompatibles.',
    stages: [
      { number:'01', title:'Diagnóstico y preparación de superficies', level:'Iniciación', summary:'El acabado se gana antes de abrir la pintura: limpieza, humedad, adherencia y planeidad.', principles:['No pintar sobre una causa activa.','La superficie dicta preparación y primer.','La limpieza final es parte del sistema.'], skills:['Inspección','Humedad conceptual','Limpieza','Desengrase','Resanes','Lijado','Selladores','Protección de áreas'], practices:[p('Panel de defectos','Crear y corregir 6 defectos en muestras.','Muestrario'),p('Prueba de adherencia simple','Comparar superficie limpia vs contaminada.','Registro'),p('Preparación de pared','Preparar 1 m² real sin pintar.','Checklist')], project:'Superficie lista para acabado' },
      { number:'02', title:'Pintura y aplicación', level:'Básico', summary:'Domina herramientas, carga, corte, rodillo, manos y control de marcas.', principles:['La película se construye en capas uniformes.','Secado entre manos importa.','Herramienta y técnica cambian textura.'], skills:['Brochas','Rodillos','Bandeja','Recorte','Carga y descarga','Solape','Número de manos','Rendimiento'], practices:[p('Muestrario de rodillos','Comparar texturas.','Panel comparativo'),p('Recorte sin cinta','Practicar 2 m lineales en tablero.','Muestra'),p('Pared de 1 m²','Aplicar sistema completo.','Panel terminado')], project:'Habitación de práctica pintada' },
      { number:'03', title:'Color, brillo y especificación', level:'Intermedio', summary:'Elige acabado por uso, luz, limpieza y sustrato, no solo por gusto.', principles:['Brillo revela defectos.','Color cambia con iluminación.','Una especificación define preparación + producto + manos.'], skills:['Mate/satinado/brillo','Color','Muestras','Primers','Compatibilidad','Lavabilidad','Cobertura','Ficha técnica'], practices:[p('Carta de muestras','Pintar 8 muestras bajo dos iluminaciones.','Muestrario'),p('Especifica 5 espacios','Elegir sistema para cocina, baño, recámara, exterior y metal.','Tabla técnica','design'),p('Calcula pintura','Estimar litros con rendimiento y manos.','Cálculo','design')], project:'Especificación de acabados de vivienda' },
      { number:'04', title:'Impermeabilización', level:'Intermedio', summary:'Comprende preparación, pendientes, grietas, refuerzos y continuidad del sistema.', principles:['Impermeabilizante no corrige mala pendiente.','Los detalles fallan antes que las áreas planas.','Cada sistema exige preparación y espesor.'], skills:['Diagnóstico de filtración','Pendientes','Limpieza','Primers','Refuerzos','Membranas','Encuentros','Mantenimiento'], practices:[p('Muestra impermeable','Aplicar sistema en charola de práctica.','Módulo probado','supervised'),p('Mapa de puntos críticos','Analizar una azotea ficticia.','Plano de riesgos','design'),p('Prueba de continuidad visual','Inspeccionar muestra por huecos y espesores.','Checklist')], project:'Detalle impermeable de azotea' },
      { number:'05', title:'Pisos y recubrimientos', level:'Intermedio', summary:'Aprende planeidad, trazos, adhesivos, juntas y cortes en recubrimientos.', principles:['El trazo evita remates pobres.','La cobertura de adhesivo importa.','Las juntas absorben tolerancias y movimiento.'], skills:['Planeidad','Trazado','Adhesivos','Loseta','Boquilla','Cortes','Juntas perimetrales','Transiciones'], practices:[p('Tablero de loseta','Colocar 6–9 piezas con junta uniforme.','Muestra'),p('Trazo centrado','Resolver recortes simétricos de un caso.','Plano de modulación','design'),p('Prueba de cobertura','Levantar una pieza de práctica y revisar adhesivo.','Registro')], project:'Módulo de piso terminado' },
      { number:'06', title:'Acabados decorativos y madera', level:'Avanzado', summary:'Explora esmaltes, barnices, tintes y texturas controlando preparación y compatibilidad.', principles:['Una muestra aprobada evita sorpresas.','Madera exige controlar humedad y lijado.','Productos incompatibles pueden fallar.'], skills:['Esmaltes','Barnices','Tintes','Selladores','Lijado entre manos','Texturas','Mascarillado','Muestras de aprobación'], practices:[p('Tabla de madera','Aplicar tres sistemas en secciones.','Muestrario'),p('Esmalte en pieza','Preparar y pintar objeto pequeño.','Pieza terminada'),p('Muestra decorativa','Repetir textura de manera consistente.','Panel')], project:'Biblioteca de acabados'
      },
      { number:'07', title:'Defectos y reparación', level:'Avanzado', summary:'Aprende a reconocer ampollas, descascaramiento, manchas, eflorescencia y diferencias de color.', principles:['Defecto visual puede tener causa física.','La reparación local debe igualar textura y brillo.','Registrar lote y sistema ayuda a repetir.'], skills:['Ampollas','Descascaramiento','Manchas','Eflorescencia','Marcas de rodillo','Parche visible','Diferencia de brillo','Retoques'], practices:[p('Atlas de defectos','Clasificar 12 casos y causa probable.','Ficha'),p('Retoque invisible','Reparar un parche pequeño intentando igualar textura.','Muestra'),p('Diagnóstico de humedad','Separar mancha superficial de humedad activa conceptualmente.','Árbol de decisión','design')], project:'Clínica de acabados' },
      { number:'08', title:'Proyecto profesional de acabados', level:'Profesional', summary:'Planea, cuantifica, ejecuta y entrega una habitación con varios sistemas compatibles.', principles:['Proteger es parte de producir.','La secuencia entre oficios evita daños.','La entrega se inspecciona con luz y criterios definidos.'], skills:['Alcance','Muestras','Cuantificación','Compras','Protección','Secuencia','Control de calidad','Entrega'], practices:[p('Presupuesto de habitación','Cuantificar pintura, protección y mano de obra ficticia.','Presupuesto','design'),p('Plan de secuencia','Coordinar resanes, primer, pintura y piso.','Plan','design'),p('Habitación final','Ejecutar un espacio real pequeño o panel completo.','Dossier de entrega','supervised')], project:'Habitación terminada y documentada' }
    ]
  },
  {
    id: 'solar',
    name: 'Energía solar',
    subtitle: 'Fotovoltaico residencial, diseño, instalación y puesta en marcha',
    target: 'Comprender, diseñar y documentar un sistema fotovoltaico residencial; practicar montaje en bancos de baja tensión y prepararte para capacitación/certificación práctica específica antes de intervenir strings o red.',
    safetyNote: 'Los arreglos fotovoltaicos pueden producir tensión peligrosa mientras reciben luz, incluso con la red desconectada. La instalación real interconectada requiere procedimientos, EPP, equipo y competencia específica.',
    stages: [
      { number:'01', title:'Fundamentos solares y seguridad', level:'Iniciación', summary:'Conecta electricidad básica con irradiancia, módulos y riesgos DC.', principles:['Un módulo energiza con luz.','DC sostenida tiene riesgos distintos a AC.','Seguridad se diseña desde el recorrido.'], skills:['Irradiancia','Celda/módulo/string','Voc','Isc','Vmp','Imp','Polaridad','Riesgos DC'], practices:[p('Mini panel solar','Medir Voc de panel pequeño bajo varias luces.','Tabla de medidas'),p('Ficha técnica','Interpretar placa/datasheet de 3 módulos.','Comparativa','design'),p('Mapa de riesgos','Analizar un sistema residencial ficticio.','Checklist','design')], project:'Banco solar de baja tensión' },
      { number:'02', title:'Arreglos y comportamiento eléctrico', level:'Básico', summary:'Aprende serie, paralelo, temperatura, sombra y curvas I-V de forma conceptual.', principles:['Serie suma tensión.','Paralelo suma corriente.','Sombra y temperatura alteran producción y límites.'], skills:['Serie','Paralelo','Strings','Temperatura','Sombra','Mismatch','Diodos bypass','Curva I-V conceptual'], practices:[p('Dos mini paneles','Comparar serie/paralelo a baja tensión.','Tabla V/I'),p('Sombra parcial','Cubrir secciones y observar respuesta.','Registro'),p('Calcula strings','Resolver 10 casos con Voc y límites ficticios.','Hoja de cálculo','design')], project:'Arreglo FV didáctico' },
      { number:'03', title:'Inversores y arquitectura', level:'Intermedio', summary:'Distingue inversor string, microinversor, optimizador y sus límites.', principles:['El inversor impone ventanas de tensión/corriente.','La arquitectura afecta sombra, mantenimiento y monitoreo.','No hay una opción universal.'], skills:['Inversor string','Microinversor','Optimizadores','MPPT','Ventana DC','Clipping','Eficiencia','Monitoreo'], practices:[p('Compara arquitecturas','Elegir solución para 4 techos ficticios.','Matriz','design'),p('Match módulo-inversor','Verificar límites con fichas de ejercicio.','Cálculo','design'),p('Lectura de monitoreo','Interpretar curvas de producción ficticias.','Diagnóstico','design')], project:'Selección de arquitectura de sistema' },
      { number:'04', title:'Levantamiento y diseño mecánico', level:'Intermedio', summary:'Evalúa superficie, orientación, inclinación, obstáculos, sombras y estructura de montaje.', principles:['El techo es parte del sistema.','La impermeabilidad no debe sacrificarse.','Cargas de viento/estructura requieren sistema y proyecto adecuados.'], skills:['Levantamiento','Orientación','Inclinación','Sombras','Obstáculos','Estructuras','Anclajes conceptuales','Sellado/impermeabilización'], practices:[p('Levantamiento de techo seguro desde suelo','Documentar orientación y obstáculos sin subir.','Ficha de sitio','design'),p('Estudio de sombra simple','Registrar sombra a varias horas o simular.','Mapa'),p('Layout de módulos','Dibujar distribución con pasillos y obstáculos.','Plano','design')], project:'Layout FV residencial' },
      { number:'05', title:'Protecciones, conductores y puesta a tierra', level:'Avanzado', summary:'Integra conductores, desconexión, protección, SPD y puesta a tierra según el diseño y normativa aplicable.', principles:['Protección depende de arquitectura y corriente disponible.','La tensión DC puede persistir.','Puesta a tierra y unión deben formar un sistema coherente.'], skills:['Conductores DC','Conductores AC','Conectores','Desconectores','Sobrecorriente','SPD','Puesta a tierra','Etiquetado'], practices:[p('Diagrama unifilar','Dibujar protecciones y desconexión de un caso.','Unifilar','design'),p('Selección de conductor','Resolver casos de ejercicio con criterios proporcionados.','Tabla','design'),p('Auditoría de etiquetas','Crear mapa de señalización.','Plan de etiquetas','design')], project:'Paquete eléctrico FV' },
      { number:'06', title:'Dimensionamiento energético', level:'Avanzado', summary:'Convierte consumo, recurso solar y pérdidas en potencia, producción y escenarios económicos.', principles:['Energía diaria/anual guía el tamaño.','Pérdidas y orientación importan.','La tarifa y perfil de consumo cambian el valor del sistema.'], skills:['Historial de consumo','kWh','HSP','Pérdidas','PR conceptual','Potencia DC','Relación DC/AC','Producción anual'], practices:[p('12 meses de consumo','Analizar un perfil ficticio.','Gráfica/tabla','design'),p('Tres tamaños de sistema','Comparar cobertura y producción.','Escenarios','design'),p('Sensibilidad','Cambiar pérdidas/orientación y comparar.','Matriz','design')], project:'Memoria de dimensionamiento' },
      { number:'07', title:'Montaje, conexión y puesta en marcha', level:'Profesional', summary:'Estudia la secuencia de instalación, inspección y pruebas siguiendo un procedimiento profesional.', principles:['Montaje mecánico y eléctrico se inspeccionan antes de energizar.','Conectores y polaridad se verifican.','Puesta en marcha requiere registro de resultados.'], skills:['Recepción de materiales','Montaje mecánico','Gestión de cables','Conectores','Polaridad','Pruebas DC','Pruebas AC conceptuales','Commissioning'], practices:[p('Rack de baja tensión','Montar mini panel y gestión de cableado.','Módulo'),p('Checklist de puesta en marcha','Crear secuencia de verificación.','Checklist','design'),p('Simulación de commissioning','Resolver lecturas ficticias y detectar anomalías.','Reporte','design')], project:'Puesta en marcha simulada de SFV' },
      { number:'08', title:'Diagnóstico y mantenimiento', level:'Profesional', summary:'Interpreta baja producción, fallas de comunicación, aislamiento y problemas mecánicos sin improvisar intervenciones peligrosas.', principles:['Comparar contra producción esperada.','Primero separar problema de recurso, DC, inversor o AC.','Mantenimiento incluye inspección mecánica y documentación.'], skills:['Baja producción','Sombra nueva','Suciedad','Conectores','Inversor','Monitoreo','Inspección visual','Mantenimiento'], practices:[p('Casos de baja producción','Diagnosticar 8 curvas ficticias.','Reporte','design'),p('Checklist anual','Diseñar inspección preventiva.','Checklist','design'),p('Termografía interpretativa','Analizar imágenes de ejemplo sin intervenir equipo.','Clasificación','design')], project:'Clínica de fallas FV' },
      { number:'09', title:'Proyecto maestro fotovoltaico', level:'Especialista', summary:'Integra levantamiento, diseño, unifilar, lista de materiales, puesta en marcha y expediente.', principles:['El proyecto debe demostrar compatibilidad completa.','Cada selección debe trazarse a una ficha técnica.','La ejecución real requiere experiencia supervisada/certificación específica.'], skills:['Sitio','Consumo','Layout','Strings','Inversor','Protecciones','BOM','Presupuesto','Commissioning','Entrega'], practices:[p('Proyecto residencial completo','Resolver un caso desde recibos ficticios hasta unifilar.','Expediente técnico','design'),p('Revisión EC0586.01','Mapear proyecto contra funciones del estándar.','Matriz de evidencias','design'),p('Defensa técnica','Responder 20 preguntas de revisión sobre tu diseño.','Acta de revisión','design')], project:'Sistema FV residencial completamente documentado' }
    ]
  }
]

export const getTradeRoute = (id: string) => tradeRoutes.find(route => route.id === id)
